#!/bin/sh
# MM firmware upgrade scripts
FIRMWARE=mm.mcs
cd /tmp
if [ ! -f "$FIRMWARE" ]; then
        exit
fi
/etc/init.d/cron stop
/etc/init.d/cgminer stop
# wait cgminer stop finish
sleep 2
mm-tools
# wait mm reboot
sleep 25
/etc/init.d/cgminer start
/etc/init.d/cron start
